In [ ]:
## 数据处理

## 均值移除

In [2]:
## 均值移除
import numpy as np
import sklearn.preprocessing as sp
raw_samples = np.array([
    [17, 100, 4000.0],
    [20., 80., 5000],
    [23., 75., 5500]
])

## 每一列均值为0 标准差为1
std_samples = sp.scale(raw_samples)
print(std_samples)
print(std_samples.mean(axis=0))
print(std_samples.std(axis=0))

std_scaler = sp.StandardScaler()
X_std = std_scaler.fit_transform(raw_samples)
print(X_std)

[[-1.22474487  1.38873015 -1.33630621]
 [ 0.         -0.46291005  0.26726124]
 [ 1.22474487 -0.9258201   1.06904497]]
[ 0.00000000e+00 -3.70074342e-17  5.18104078e-16]
[1. 1. 1.]
[[-1.22474487  1.38873015 -1.33630621]
 [ 0.         -0.46291005  0.26726124]
 [ 1.22474487 -0.9258201   1.06904497]]


## 范围缩放

In [3]:
arr = np.array([17, 20 ,23])
arr_min = (arr - arr.min())
# arr_scale = arr_min / (arr.max() - arr.min())
arr_scale = arr_min / arr_min.max()
print(arr)
print(arr_min)
print(arr_scale)

### 特征缩放范围(0,1)--》可以自由变更
min_max_scaler = sp.MinMaxScaler(feature_range=(0, 1))
### 只能接受二维数组。方法是fit_transform--拟合转化, fit是拟合
print(min_max_scaler.fit_transform(arr.reshape(-1, 1)))

## 线性拟合
A = np.array([
    [17, 1],
    [23, 1]
])
B = np.array([
    [0],
    [1]
])
X = np.linalg.lstsq(A, B)
print(X[0][0], X[0][1])
print(X[0][0]*20 + X[0][1])

def min_max_scaler_func(X):
    X_copy = X.copy()
    for col in X_copy.T:
        col_min = col.min()
        col_max = col.max()
        A = np.array([[col_min, 1], [col_max, 1]])
        B = np.array([[0], [1]])
        x = np.linalg.lstsq(A, B)[0]
        col *= x[0]
        col += x[1]
    return X_copy
# min_max_scaler_func(raw_samples)

print(min_max_scaler.fit_transform(raw_samples))
print(min_max_scaler_func(raw_samples))

[17 20 23]
[0 3 6]
[0.  0.5 1. ]
[[0. ]
 [0.5]
 [1. ]]
[0.16666667] [-2.83333333]
[0.5]
[[0.         1.         0.        ]
 [0.5        0.2        0.66666667]
 [1.         0.         1.        ]]
[[2.22044605e-15 1.00000000e+00 8.88178420e-16]
 [5.00000000e-01 2.00000000e-01 6.66666667e-01]
 [1.00000000e+00 1.33226763e-15 1.00000000e+00]]


In [4]:
### 标准化 -- 列级别

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import sklearn.preprocessing as sp
import numpy as np

raw_samples = np.array([
    [17, 100, 4000.0],
    [20., 80., 5000],
    [23., 75., 5500]
])

## 每一列均值为0 标准差为1
std_samples = sp.scale(raw_samples)
print(std_samples)
print(std_samples.mean(axis=0))
print(std_samples.std(axis=0))

std_scaler = sp.StandardScaler()
X_std = std_scaler.fit_transform(raw_samples)
print(X_std)

[[-1.22474487  1.38873015 -1.33630621]
 [ 0.         -0.46291005  0.26726124]
 [ 1.22474487 -0.9258201   1.06904497]]
[ 0.00000000e+00 -3.70074342e-17  5.18104078e-16]
[1. 1. 1.]
[[-1.22474487  1.38873015 -1.33630621]
 [ 0.         -0.46291005  0.26726124]
 [ 1.22474487 -0.9258201   1.06904497]]


In [5]:
### 范围缩放 -- 列级别

arr = np.array([17, 20 ,23])
arr_min = (arr - arr.min())
# arr_scale = arr_min / (arr.max() - arr.min())
arr_scale = arr_min / arr_min.max()
print(arr)
print(arr_min)
print(arr_scale)

### 特征缩放范围(0,1)--》可以自由变更
min_max_scaler = sp.MinMaxScaler(feature_range=(0, 1))
### 只能接受二维数组。方法是fit_transform--拟合转化, fit是拟合
print(min_max_scaler.fit_transform(arr.reshape(-1, 1)))

## 线性拟合
A = np.array([
    [17, 1],
    [23, 1]
])
B = np.array([
    [0],
    [1]
])
X = np.linalg.lstsq(A, B)
print(X[0][0], X[0][1])
print(X[0][0]*20 + X[0][1])

def min_max_scaler_func(X):
    X_copy = X.copy()
    for col in X_copy.T:
        col_min = col.min()
        col_max = col.max()
        A = np.array([[col_min, 1], [col_max, 1]])
        B = np.array([[0], [1]])
        x = np.linalg.lstsq(A, B)[0]
        col *= x[0]
        col += x[1]
    return X_copy
# min_max_scaler_func(raw_samples)

print(min_max_scaler.fit_transform(raw_samples))
print(min_max_scaler_func(raw_samples))

[17 20 23]
[0 3 6]
[0.  0.5 1. ]
[[0. ]
 [0.5]
 [1. ]]
[0.16666667] [-2.83333333]
[0.5]
[[0.         1.         0.        ]
 [0.5        0.2        0.66666667]
 [1.         0.         1.        ]]
[[2.22044605e-15 1.00000000e+00 8.88178420e-16]
 [5.00000000e-01 2.00000000e-01 6.66666667e-01]
 [1.00000000e+00 1.33226763e-15 1.00000000e+00]]


## 正则化

In [ ]:
### 正则化(归一化) -- 处理的是行级别

### l2范数 -- 向量中每个元素平方和
r = sp.normalize(raw_samples, norm='l2')
print(r)
### l1范数 -- 向量中每个元素绝对值之和
r = sp.normalize(raw_samples, norm='l1')
print(r)

nor_samples = raw_samples.copy()
for row in nor_samples:
    row /= abs(row).sum()
print('my nor:', nor_samples)

## 二值化

In [7]:
### 二值化
np.random.seed(1)
arr = np.random.normal(0, 1, size=(10, 10))

## 创建二值化器
bin = sp.Binarizer(threshold=0.5)
bin_samples = bin.transform(arr)
print(arr)
print("*"*45)
print(bin_samples)
print("*"*45)
print(bin.fit_transform(arr))

arr2 = arr.copy()
arr2[arr2 >= 0.5] = 1
arr2[arr2 < 0.5] = 0
print("*"*45)
print(arr2)

[[ 1.62434536 -0.61175641 -0.52817175 -1.07296862  0.86540763 -2.3015387
   1.74481176 -0.7612069   0.3190391  -0.24937038]
 [ 1.46210794 -2.06014071 -0.3224172  -0.38405435  1.13376944 -1.09989127
  -0.17242821 -0.87785842  0.04221375  0.58281521]
 [-1.10061918  1.14472371  0.90159072  0.50249434  0.90085595 -0.68372786
  -0.12289023 -0.93576943 -0.26788808  0.53035547]
 [-0.69166075 -0.39675353 -0.6871727  -0.84520564 -0.67124613 -0.0126646
  -1.11731035  0.2344157   1.65980218  0.74204416]
 [-0.19183555 -0.88762896 -0.74715829  1.6924546   0.05080775 -0.63699565
   0.19091548  2.10025514  0.12015895  0.61720311]
 [ 0.30017032 -0.35224985 -1.1425182  -0.34934272 -0.20889423  0.58662319
   0.83898341  0.93110208  0.28558733  0.88514116]
 [-0.75439794  1.25286816  0.51292982 -0.29809284  0.48851815 -0.07557171
   1.13162939  1.51981682  2.18557541 -1.39649634]
 [-1.44411381 -0.50446586  0.16003707  0.87616892  0.31563495 -2.02220122
  -0.30620401  0.82797464  0.23009474  0.76201118]
 [

## 独热编码

In [ ]:
### 独热编码
## 按列的方向来计算类别,因为第一类代表同一个特征
## 第一列的值有4种:ABCD, 那么第一列的编码
## A: [1, 0, 0, 0]
## B: [0, 1, 0, 0]
## C: [0, 0, 1, 0]
## D: [0, 0, 0, 1]
## 第二列的有三种:BAD
## A: [1, 0, 0]
## B: [0, 1, 0]
## D: [0, 0, 1]
## ...以此类推,注意虽然都是A的值,但它们的编码可能不一样,要根据种类来编码

arr = np.array(
    [
        [1, 3, 2],
        [7, 5, 4],
        [1, 8 ,6],
        [7, 3, 9]
    ]
)

one_encoder = sp.OneHotEncoder()
print(one_encoder.fit_transform(arr))

## spare_output 是否采用紧缩模式 false则采用稀疏矩阵 true采用紧缩格式
one_encoder = sp.OneHotEncoder(sparse_output=False)
print(one_encoder.fit_transform(arr))

###
# {‘error’, ‘ignore’}, default=’error’ 在转换过程中遇到未知分类特征时，是引发错误还是忽略（默认为引发）。当此参数设置为“ignore”并且在转换过程中遇到未知类别时，这一特征的 one-hot 编码列将全置为 0。在逆变换中，未知类别将表示为 None

arr = np.array(['A', 'B', 'C', 'D', 'E', 'F']).reshape(2, 3)
# one_encoder = sp.OneHotEncoder(sparse_output=False, handle_unknown='error')
one_encoder = sp.OneHotEncoder(sparse_output=False, handle_unknown='ignore')
one_encoder.fit(arr)
print(one_encoder.transform(arr))
print(one_encoder.transform([['A', 'G', 'C'], ['B', 'D', 'E']]))

## 反编码
print(one_encoder.inverse_transform([[0, 1, 1, 0, 0, 1]]))


##############################
## 2个数   3个数   4个数
##  1       3      2
##  7       5      4
##  1       8      6
##  7       3      9
##
## 每个数字编码
## 1-10  3-100  2-1000
## 7-01  5-010  4-0100
##       8-001  6-0010
##              9-0001
##
## 最终样本矩阵
## [1. 0. 1. 0. 0. 1. 0. 0. 0.]
## [0. 1. 0. 1. 0. 0. 1. 0. 0.]
## [1. 0. 0. 0. 1. 0. 0. 1. 0.]
## [0. 1. 1. 0. 0. 0. 0. 0. 1.]
##

In [1]:

from sklearn.preprocessing import OneHotEncoder
y = [['A', 'B', 'C', 'D'], ['B', 'A', 'B', 'A'], ['C', 'D', 'A', 'B'],
     ['D','A', 'C', 'B']]
print(y[0])
print(y[1])
print(y[2])
print(y[3])
encoder = OneHotEncoder(sparse_output=False)
y_encoder = encoder.fit_transform(y)
print(y_encoder)

['A', 'B', 'C', 'D']
['B', 'A', 'B', 'A']
['C', 'D', 'A', 'B']
['D', 'A', 'C', 'B']
[[1. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 1.]
 [0. 1. 0. 0. 1. 0. 0. 0. 1. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 1. 1. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 1. 0. 0. 0. 0. 1. 0. 1. 0.]]


## 标签编码

In [5]:
### 标签编码
import numpy as np
import sklearn.preprocessing as sp
arr = np.array(['bmw', 'ford', 'audi', 'toyota', 'redflag', 'ford'])
lbe = sp.LabelEncoder()
result = lbe.fit_transform(arr)
print(result)

### 反编码
lbe.inverse_transform(result)

[1 2 0 4 3 2]


array(['bmw', 'ford', 'audi', 'toyota', 'redflag', 'ford'], dtype='<U7')

In [10]:
### 欠拟合 和 过拟合
# 欠拟合,模型过于简单,对于训练数据和测试数据,都无法给出足够高的预测精度
# 过拟合,模型过于复杂,对于训练数据能够给出较高的预测精度,但对于测试数据预测精度较低
# 一个性能可以接受的学习模型应该对训练数据和测试数据都有接近的预测精度,而且精度不能太低
#
# 训练数据R1, 预测数据R1
# 0.3         0.4         欠拟合,过于简单,无法反应数据规则
# 0.9         0.2         过拟合,过于复杂,太特殊,缺乏一般性,泛化性差
# 0.7         0.6         可接受,复杂度适中,既能反应数据规则,同时又不失一般性