In [1]:
import numpy as np

## numpy基础

- ndarray数组
  np.ndarray类的对象表示n维数组。

In [2]:
ary = np.array([1, 2, 3])
print(type(ary))

<class 'numpy.ndarray'>


## 内存中的ndarray对象
- 元数据(metadata)
- dim, dimensions, dtype, data
- ![结构](./资料/numpy_meta.png)



In [ ]:
print(ary * 10)
print(ary + ary)
print(ary.ndim, ary.size, ary.shape, ary.dtype, ary.data)

In [5]:
## [开始值,结束值),步长
np.arange(0, 5, 1)

array([0, 1, 2, 3, 4])

In [12]:
# [开始值start, 结束值end], 划分个数num
# 步长: (end - start) / (num - 1)
np.linspace(0, 5, 5)
np.linspace(0, 5, 9)
np.linspace(5, 10, 6)

array([ 5.,  6.,  7.,  8.,  9., 10.])

In [20]:
np.zeros(10)
np.zeros(3, dtype=int)
val = np.zeros((5, 5), dtype=int)
val[0, 0] = 1
print(val)

[[1 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [28]:
ones = np.ones((5, 5), dtype=int)
print(ones)
np.zeros(10, dtype=np.float32)
np.zeros(4, dtype=np.bool)
np.ones(5, dtype=np.bool)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


array([ True,  True,  True,  True,  True])

In [24]:
like = np.zeros_like(ones)
print(like)
print(np.ones_like(like))

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [4]:
arr = np.arange(0, 5, 1)
arr2 = np.array([[1, 10, 3], [4, 0, 6]])
print(arr.shape, arr2.shape, arr2.shape[0], len(arr2), arr2.size)

(5,) (2, 3) 2 2 6


In [44]:
print(np.reshape(arr2, (1, 6)))
print(np.reshape(arr2, (1, 6), order='F'))
print(np.reshape(arr2, (1, 6), order='C'))

print(np.reshape(arr2, (1, -1)))
print(np.reshape(arr2, (2, -1)))
print(np.reshape(arr2, (3, -1)))

[[ 1 10  3  4  0  6]]
[[ 1  4 10  0  3  6]]
[[ 1 10  3  4  0  6]]
[[ 1 10  3  4  0  6]]
[[ 1 10  3]
 [ 4  0  6]]
[[ 1 10]
 [ 3  4]
 [ 0  6]]


In [51]:
## 元数据修改

a1 = np.array([1, 2, 3, 4, 5, 6, 7 ,8])
print(a1.shape)
a1.shape = (2, 4)
print(a1.shape, a1)
print(a1.ndim, a1.size, a1.shape, a1.dtype)

(8,)
(2, 4) [[1 2 3 4]
 [5 6 7 8]]
2 8 (2, 4) int64
float64 [[4.9e-324 9.9e-324 1.5e-323 2.0e-323]
 [2.5e-323 3.0e-323 3.5e-323 4.0e-323]]


In [5]:
a2 = np.arange(10)
print('a2', a2, a2.dtype)
## 可以改,但最好不要,会导致数据错乱,因为读取的数据字节变化了, 要改使用astype方法
a2.dtype = np.int32
print('a2 modify:', a2, a2.dtype)

### astype 会新建一个数组对象, 不会修改原始对象
a3 = np.arange(10)
print('a3 :', a3, a3.dtype)
a3_1 = a3.astype(np.int8)
print('a3_1 :', a3_1, a3_1.dtype)
a3_2 = a3.astype(np.float64)
print('a3_2 :', a3_2, a3_2.dtype)

a2 [0 1 2 3 4 5 6 7 8 9] int64
a2 modify: [0 0 1 0 2 0 3 0 4 0 5 0 6 0 7 0 8 0 9 0] int32
a3 : [0 1 2 3 4 5 6 7 8 9] int64
a3_1 : [0 1 2 3 4 5 6 7 8 9] int8
a3_2 : [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.] float64


In [6]:
## 变形
ary = np.arange(12).reshape(3, 4)
ary.ndim, ary.shape, ary.size, len(ary)

(2, (3, 4), 12, 3)

In [7]:
## 读取
ary = np.arange(24).reshape(2, 3, 4)
print(ary)
print(ary[1])
print(ary[1, 2])
print(ary[1, 2, 3])
print(ary[1][2])
print(ary[1][2][3])

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[20 21 22 23]
23
[20 21 22 23]
23


In [8]:
for i in range(ary.shape[0]):
    for j in range(ary.shape[1]):
        for k in range(ary.shape[2]):
            print(ary[i, j, k])

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


### numpy的数据类型 和 缩写
可以查看图片 numpy数据类型和缩写.png 或访问 https://cloud.tencent.com/developer/article/1755021

In [9]:
var = np.dtype(np.float64)
print(var, type(var))

float64 <class 'numpy.dtypes.Float64DType'>


In [10]:
### 自定义复合类型--类

data = [
    ('zhangsan', [98, 80, 85], 15),
    ('lisi', [92, 81, 83], 16),
    ('wangwu', [95, 85, 95], 14),
]

# scores = np.array(data)
## U在基础数据类型时,会自动推断长度
data2 = np.array(['aa', 'bbb', 'cccc', 'ddddd'], dtype='U')
print(data2, data2.dtype)

## 这里不能直接写U,不会自动推断结构化数据的长度,解决办法,要么用object,要么用一个大长度(不推荐,浪费空间)
scores = np.array(data, dtype='U, 3i4, i4')
print(scores, scores.dtype)
scores = np.array(data, dtype='O, 3i4, i4')
print(scores, scores.dtype)
### 结构化数据怎么访问 f1, f2代表field1 field2
print('read:', scores[0]['f1'][0])
print('--'*30)
score2 = np.array(data, dtype=[('name', 'str', 2), ('scores', 'int32', 3), ('age', 'int32', 1)])
## 这个时候就没有f0,f1了,已经有明确的字段名字了
print('read:', score2[0]['scores'][0])
print(score2, score2.dtype)
print('--'*30)
score3 = np.array(data, dtype={'names':['name', 'scores', 'age'], 'formats':[
    'U10', '3int32', 'int32'
]})
print('read:', score3[0]['scores'][0])
print(score3, score3.dtype, scores.itemsize)
print('--'*30)

### 不推荐,要控制字节数, 知道就好了
# score4 = np.array(data, dtype={'name': ('U10', 0), 'scores':('3int32', 16), 'age':('int32', 28)})
# print('read:', score4[0]['scores'][0])

## 第一种设置dtype的方式
# scores = np.array(data, dtype='U3, 3i4, i4')
# scores = np.array(data, dtype='<U10, 3i4, i4')
# scores = np.array(data, dtype='O, 3i4, i4')

## 第二种设置dtype的方式
# score2 = np.array(data, dtype=[('name', 'str', 2), ('scores', 'int32', 3), ('age', 'int32', 1)])

## 第三种设置dtype的方式
# score3 = np.array(data, dtype={'names':['name', 'scores', 'age'], 'formats':[
#     'U10', '3int32', 'int32'
# ]})


['aa' 'bbb' 'cccc' 'ddddd'] <U5
[('', [98, 80, 85], 15) ('', [92, 81, 83], 16) ('', [95, 85, 95], 14)] [('f0', '<U'), ('f1', '<i4', (3,)), ('f2', '<i4')]
[('zhangsan', [98, 80, 85], 15) ('lisi', [92, 81, 83], 16)
 ('wangwu', [95, 85, 95], 14)] [('f0', 'O'), ('f1', '<i4', (3,)), ('f2', '<i4')]
read: 98
------------------------------------------------------------
read: 98
[('zh', [98, 80, 85], [15]) ('li', [92, 81, 83], [16])
 ('wa', [95, 85, 95], [14])] [('name', '<U2'), ('scores', '<i4', (3,)), ('age', '<i4', (1,))]
------------------------------------------------------------
read: 98
[('zhangsan', [98, 80, 85], 15) ('lisi', [92, 81, 83], 16)
 ('wangwu', [95, 85, 95], 14)] [('name', '<U10'), ('scores', '<i4', (3,)), ('age', '<i4')] 24
------------------------------------------------------------


In [11]:
## 测试日期类型的数据 datetime64
from datetime import datetime

data = ['2025', '2025-01-12', '2025-12', '2025-12-20 12:23:23']
date_arr  = np.array(data)
print(date_arr, date_arr.dtype)
date_arr = np.array(data, dtype='datetime64[D]')
print(date_arr, date_arr.dtype)
date_arr = np.array(data, dtype='M8[s]')
print(date_arr, date_arr.dtype)
### 两个是完全不同的日期类型
print(date_arr[0], type(date_arr[0]), datetime.now(), type(datetime.now()))

## 日期差
dis = date_arr[1] - date_arr[2]
print(dis, type(dis))

date_arr = date_arr.astype('M8[D]')
dis = date_arr[1] - date_arr[2]
print(dis, type(dis))

['2025' '2025-01-12' '2025-12' '2025-12-20 12:23:23'] <U19
['2025-01-01' '2025-01-12' '2025-12-01' '2025-12-20'] datetime64[D]
['2025-01-01T00:00:00' '2025-01-12T00:00:00' '2025-12-01T00:00:00'
 '2025-12-20T12:23:23'] datetime64[s]
2025-01-01T00:00:00 <class 'numpy.datetime64'> 2025-04-15 00:16:29.082591 <class 'datetime.datetime'>
-27907200 seconds <class 'numpy.timedelta64'>
-323 days <class 'numpy.timedelta64'>


In [12]:
### 视图维度变更
a = np.arange(12)
print(a, a.shape)
b = a.reshape(3, 4)
print(b, b.shape)
c = a.ravel()
print(c, c.shape)
d = a.repeat(3, axis=0)
print(d, d.shape)
e = a.reshape(3, 4).repeat(3, axis=0)
print(e, e.shape)
f = a.reshape(3, 4).repeat(3, axis=1)
print(f, f.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11] (12,)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] (3, 4)
[ 0  1  2  3  4  5  6  7  8  9 10 11] (12,)
[ 0  0  0  1  1  1  2  2  2  3  3  3  4  4  4  5  5  5  6  6  6  7  7  7
  8  8  8  9  9  9 10 10 10 11 11 11] (36,)
[[ 0  1  2  3]
 [ 0  1  2  3]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 4  5  6  7]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 8  9 10 11]
 [ 8  9 10 11]] (9, 4)
[[ 0  0  0  1  1  1  2  2  2  3  3  3]
 [ 4  4  4  5  5  5  6  6  6  7  7  7]
 [ 8  8  8  9  9  9 10 10 10 11 11 11]] (3, 12)


In [13]:
## 一维变更
aa = np.arange(12)
bb = aa.ravel() ## 浅拷贝
bb[0] = 100
print(bb, aa)
cc = aa.flatten() ## 深拷贝
cc[1] = 10000
print(cc, aa)

## 就地变维 -- 直接更改原对象
aa.shape = (3, 4)
print(aa.shape, aa)
print('----------')
aa.resize((4, 3))
print(aa, aa.shape)
print('----------')
aa.resize((6, 2)) ## 不能写-1, 这个和reshape有本质区别
print(aa, aa.shape)


[100   1   2   3   4   5   6   7   8   9  10  11] [100   1   2   3   4   5   6   7   8   9  10  11]
[  100 10000     2     3     4     5     6     7     8     9    10    11] [100   1   2   3   4   5   6   7   8   9  10  11]
(3, 4) [[100   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]
----------
[[100   1   2]
 [  3   4   5]
 [  6   7   8]
 [  9  10  11]] (4, 3)
----------
[[100   1]
 [  2   3]
 [  4   5]
 [  6   7]
 [  8   9]
 [ 10  11]] (6, 2)


In [14]:
a = np.arange(12)
print(a)
print(a[:3])
print(a[3:6])
print(a[6:])
print(a[:-1])
print(a[:-4:-1])
print(a[-4:-7:-1])
print(a[::])
print(a[:])
print(a[::2])
print(a[1::3])
print(a[4::4])


b = a[2:6] ##浅拷贝 -- 这个是数组
print(b)
b[3] = 99999
print(b, a)

xx = [i for i in range(12)]
yy = xx[2:6] ##深拷贝 -- 这个是列表
yy[3] = 888888
print(xx, yy)


[ 0  1  2  3  4  5  6  7  8  9 10 11]
[0 1 2]
[3 4 5]
[ 6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10]
[11 10  9]
[8 7 6]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  2  4  6  8 10]
[ 1  4  7 10]
[4 8]
[2 3 4 5]
[    2     3     4 99999] [    0     1     2     3     4 99999     6     7     8     9    10    11]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11] [2, 3, 4, 888888]


In [15]:
## 多位数组切片
a = np.arange(1, 28).reshape(3, 3, 3)
print(a[1,1,1])
print(a[1,:,:])
print(a[1,:, 1])

14
[[10 11 12]
 [13 14 15]
 [16 17 18]]
[11 14 17]


In [16]:
### 掩码运算
c = np.array([[1, 100], [200, 2]])
mask = c > 50
print(mask)
c[mask] = 999999 ## 掩码的为true的位置进行赋值
print(c)
print(c[mask]) ## 经过掩码后,变成一维数组

print('------------------------------')
a = np.arange(0, 100).reshape(10, 10)
print(a[(a % 3 == 0) & (a % 5 == 0)])
print(a[(a % 3 == 0) | (a % 5 == 0)])


cc = np.array(['A', 'B', 'C', 'D'])
mask = [3, 0 , 2, 0 , 0 , 1, 3, 0 , 1] ##掩码赋值
print(cc[mask])

[[False  True]
 [ True False]]
[[     1 999999]
 [999999      2]]
[999999 999999]
------------------------------
[ 0 15 30 45 60 75 90]
[ 0  3  5  6  9 10 12 15 18 20 21 24 25 27 30 33 35 36 39 40 42 45 48 50
 51 54 55 57 60 63 65 66 69 70 72 75 78 80 81 84 85 87 90 93 95 96 99]
['D' 'A' 'C' 'A' 'A' 'B' 'D' 'A' 'B']


In [17]:
## 多维度数组组合拆分
a = np.arange(0, 6).reshape(2, 3)
b = np.arange(7, 13).reshape(2, 3)

c = np.vstack((a, b))
print(c)

d = np.hstack((a, b))
print(d)

e, f = np.vsplit(c, 2)
print(e, f)

h, i = np.hsplit(d, 2)
print(h, i)

aa = np.dstack((a, b))
print(aa)


[[ 0  1  2]
 [ 3  4  5]
 [ 7  8  9]
 [10 11 12]]
[[ 0  1  2  7  8  9]
 [ 3  4  5 10 11 12]]
[[0 1 2]
 [3 4 5]] [[ 7  8  9]
 [10 11 12]]
[[0 1 2]
 [3 4 5]] [[ 7  8  9]
 [10 11 12]]
[[[ 0  7]
  [ 1  8]
  [ 2  9]]

 [[ 3 10]
  [ 4 11]
  [ 5 12]]]


In [19]:
## pad操作
x = np.array([1, 2, 3, 4]).reshape(2, 2)
y = np.array([4, 5])
## pad_width的意思:before, after, 前面插入几个,后面插入几个
z = np.pad(y, pad_width=(1, 2), mode='constant', constant_values=0)
print(z)
## pad_width是数组时, 第一个代表一维方向,第二个代表二维方向,也是before和after的意思
m = np.pad(x, pad_width=[(1, 2),(3, 4)], mode='constant', constant_values=0)
print(m)

[0 4 5 0 0]
[[0 0 0 0 0 0 0 0 0]
 [0 0 0 1 2 0 0 0 0]
 [0 0 0 3 4 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]


In [20]:
## 组合和拆分的终极大招
m = np.arange(1, 10).reshape(3, 3)
n = np.arange(11, 20).reshape(3, 3)
x = np.concatenate([m, n], axis=0)
print(x)
y = np.concatenate([m, n], axis=1)
print(y)
x0, x1 = np.split(x, 2, axis=0)
print(x0, x1)
y0, y1 = np.split(y, 2, axis=1)
print(y0, y1)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]
[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]
[[1 2 3]
 [4 5 6]
 [7 8 9]] [[11 12 13]
 [14 15 16]
 [17 18 19]]
[[1 2 3]
 [4 5 6]
 [7 8 9]] [[11 12 13]
 [14 15 16]
 [17 18 19]]


In [21]:
## ndarray其他属性

a = np.arange(10).reshape(2, 5)
## int64-8字节 总共占用8*10=80字节
print(a.itemsize, a.nbytes, a.T)

## a.flat扁平迭代器
for x in a.flat:
    print(x)

8 80 [[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]
0
1
2
3
4
5
6
7
8
9
